const GET_LOGGED_IN_USER = 'GET LOGGED IN USER';
const LOGIN = 'LOGIN';
const REGISTER = 'REGISTER';
const LOGOUT = 'LOGOUT';

const LOGIN_SUCCESS = 'LOGIN SUCCESS';
const REGISTER_SUCCESS = 'REGISTER SUCCESS';
const LOGOUT_SUCCESS = 'LOGOUT SUCCESS';

const LOGIN_ERROR = 'LOGIN ERROR';
const REGISTER_ERROR = 'REGISTER_ERROR';
const LOGOUT_ERROR = 'LOGOUT ERROR';



export {
    GET_LOGGED_IN_USER,
    LOGIN,
    REGISTER,
    LOGOUT,
    LOGIN_SUCCESS,
    REGISTER_SUCCESS,
    LOGOUT_SUCCESS,
    LOGIN_ERROR,
    REGISTER_ERROR,
    LOGOUT_ERROR
}